# Project config for Toolmaster of Brainerd, written by device-cookiecutter

project:
  name: {{cookiecutter.project_name}}
  slug: {{cookiecutter.project_slug}}
  pkg: {{cookiecutter.pkg_name}}
  description: {{cookiecutter.project_description}}